name: truckflow
description: Free Waze-style truck navigation for European FTL drivers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4

  # Navigation
  go_router: ^13.2.0

  # Maps & Location
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0

  # Network
  dio: ^5.4.1

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Authentication
  flutter_secure_storage: ^9.0.0

  # Utilities
  uuid: ^4.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # UI
  flutter_svg: ^2.0.10
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  path_provider: ^2.1.5
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  speech_to_text: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
